import { DefaultTheme } from "react-native-paper";

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: "#6366f1",
    primaryContainer: "#e0e7ff",
    secondary: "#8b5cf6",
    secondaryContainer: "#f3e8ff",
    tertiary: "#ec4899",
    tertiaryContainer: "#fce7f3",
    surface: "#ffffff",
    surfaceVariant: "#f8fafc",
    background: "#f8fafc",
    error: "#ef4444",
    errorContainer: "#fef2f2",
    onPrimary: "#ffffff",
    onSecondary: "#ffffff",
    onTertiary: "#ffffff",
    onSurface: "#1f2937",
    onSurfaceVariant: "#6b7280",
    onBackground: "#1f2937",
    onError: "#ffffff",
    outline: "#d1d5db",
    border: "#e5e7eb",
    shadow: "#000000",
    inverseSurface: "#374151",
    inverseOnSurface: "#f9fafb",
    inversePrimary: "#a5b4fc",
  },
  fonts: {
    ...DefaultTheme.fonts,
    headlineLarge: {
      fontFamily: "System",
      fontSize: 32,
      fontWeight: "bold",
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: "System",
      fontSize: 28,
      fontWeight: "bold",
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: "System",
      fontSize: 24,
      fontWeight: "bold",
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: "System",
      fontSize: 22,
      fontWeight: "600",
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: "System",
      fontSize: 16,
      fontWeight: "600",
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: "System",
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: "System",
      fontSize: 16,
      fontWeight: "400",
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: "System",
      fontSize: 14,
      fontWeight: "400",
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: "System",
      fontSize: 12,
      fontWeight: "400",
      lineHeight: 16,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    round: 50,
  },
};
